# Site
name: "The Future of AI Regulation"
title: "AI Regulation"
description: "Oxford x Goodenough"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
#baseurl: /
#google_analytics: 'UA-46278016-1'
#disqus: 'demowebsite'
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  tesskonrad:
    name: Tess Buckley and Konrad Kollnig
    display_name: Tess and Konrad
    avatar: 'assets/images/tess-konrad.jpg'
    description: "Tess: MA Philosophy and Artificial Intelligence, NCH at Northeastern University; Konrad: PhD Student, Department of Computer Science, University of Oxford"
  konrad:
    name: Konrad Kollnig
    display_name: Konrad Kollnig
    avatar: 'assets/images/konrad.jpg'
    web: https://kollnig.net
    twitter: https://twitter.com/FascinatingTech
    description: "PhD Student, Department of Computer Science, University of Oxford"
  tess:
    name: Tess Buckley
    display_name: Tess Buckley 
    avatar: 'assets/images/tess.jpg'
    web: https://www.linkedin.com/in/tess-buckley-a9580b166/
    description: "MA Philosophy and Artificial Intelligence, NCH at Northeastern University"
  david:
    name: David Neuberger
    display_name: David Neuberger
    avatar: 'assets/images/david.jpg'
    description: "English Judge and Former President of the UK Supreme Court"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
#adsense-data-ad-client: "ca-pub-3412143450191416"
#adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
