# Site
name: "The Future of AI Regulation"
title: "AI Regulation"
description: "Oxford x Goodenough"
logo: 'assets/images/logo-full.png'
favicon: 'assets/images/logo.png'
#baseurl: /
#google_analytics: 'UA-46278016-1'
#disqus: 'demowebsite'
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  david:
    name: David Neuberger
    display_name: David Neuberger
    avatar: 'assets/images/david.jpg'
    description: "The Rt Hon The Lord David Neuberger of Abbotsbury HonFRS"
    web: https://www.oeclaw.co.uk/barristers/profile/lord-neuberger-of-abbotsbury
  tesskonrad:
    name: Tess Buckley and Konrad Kollnig
    display_name: Tess and Konrad
    avatar: 'assets/images/tess-konrad.jpg'
    description: "Tess: MA Philosophy and Artificial Intelligence, NCH at Northeastern University; Konrad: PhD Student, Department of Computer Science, University of Oxford"
  tess:
    name: Tess Buckley
    display_name: Tess Buckley 
    avatar: 'assets/images/tess.jpg'
    web: https://www.linkedin.com/in/tess-buckley-a9580b166/
    description: "MA Philosophy and Artificial Intelligence, NCH at Northeastern University"
  konrad:
    name: Konrad Kollnig
    display_name: Konrad Kollnig
    avatar: 'assets/images/konrad.jpg'
    web: https://kollnig.net
    twitter: https://twitter.com/FascinatingTech
    description: "PhD Student, Department of Computer Science, University of Oxford"
  luke:
    name: Luke Thorburn
    display_name: Luke Thorburn
    avatar: 'assets/images/luke.jpg'
    web: https://lukethorburn.com
    description: "Doctoral candidate in Safe & Trusted AI at King's College London"
  Nigel:
    name: Nigel Shadbolt
    display_name: Nigel Shadbolt
    avatar: assets/images/shadbolt.jpeg
    web: https://www.jesus.ox.ac.uk/about-jesus-college/our-community/people/nigel-shadbolt/
    description: "Professor Sir Nigel Shadbolt FRS from the University of Oxford"
  Julie:
    name: Dr Julie Maxton
    display_name: Dr Julie Maxton
    avatar: assets/images/Maxton.jpg
    web: https://royalsociety.org/people/julie-maxton-10021/ 
    description: "Executive Director of the Royal Society" 
  Max:
    name: Dr Max Van Kleek
    display_name: Dr Max Van Kleek
    avatar: assets/images/Kleek.png
    web: https://hip.cat/emax/about
    description: "Associate Professor of Human-Computer Interaction with the Department of Computer Science, at the University of Oxford"
  Ulrik:
    name: Ulrik Lyngs
    display_name: Ulrik Lyngs
    avatar: assets/images/Lyngs.jpeg
    web: https://ulriklyngs.com 
    description: "Carlsberg Foundation Oxford Visiting Fellow at the University of Oxford’s Human Centred Computing group"
  Jake:
    name: Jake Stein
    display_name: Jake Stein 
    avatar: assets/images/stein.jpg
    web: https://www.linkedin.com/in/jake-stein-he-him-b7b4b594/?originalSubdomain=uk
    description: "Oxford Martin School Doctoral Researcher for Ethical Web and Data Architectures in the Age of AI"
  Ge:
    name: Ge Wang
    display_name: Ge Wang 
    avatar: assets/images/wang.jpeg
    web: https://www.tiffanygewang.com 
    description: "Dphil student in the Department of Computer Science at University of Oxford"
  Claudine:
    name: Claudine Tinsman
    display_name: Claudine Tinsman 
    avatar: assets/images/Tinsman.jpg
    web: https://www.cs.ox.ac.uk/people/claudine.tinsman/
    description: "DPhil candidate in Cyber Security"
  See:
    name: Zheng Hong Sebastian See
    display_name: Zheng Hong Sebastian See
    avatar: assets/images/see.jpeg
    web: https://www.linkedin.com/in/zheng-hong-sebastian-see/?originalSubdomain=uk 
    description: "LLB and BCL Lawyer and BVS Student"
  Rachel:
    name: Rachel Venn
    display_name: Rachel Venn
    avatar: assets/images/Venn.jpeg
    web: https://www.linkedin.com/in/rachelvenn/
    description: "MSc Space Science and Engineering at UCL"
  Karan:
    name: Dr Karan Mehta
    display_name: Dr Karan Mehta
    avatar: assets/images/Mehta.jpeg
    web: https://www.linkedin.com/in/dr-karan-mehta-73272277/?originalSubdomain=uk 
    description: "Founder & CEO at Bluezone Insurance" 
  Alexandra:
    name: Alexandra Houston
    display_name: Alexandra Houston
    avatar: assets/images/Houston.jpeg
    web: https://www.linkedin.com/in/alexandra-houston-76aab4ba/
    description: "Public Health MSc Student at LSHTM"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
#adsense-data-ad-client: "ca-pub-3412143450191416"
#adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
